<!DOCTYPE html>    
<html>
<head id="head" >
    <script type='text/javascript' src='html/javascript/default/prototype.js'></script>
    <script type="text/javascript">
          

          
          function haz(){
              
                      var json = '{"id":["key_name"],"about":["author","date","keywords","state"]}';



    var parsed = JSON.parse(json);

    console.log(parsed['id']);
    
     newString = JSON.stringify(parsed);
    
       console.log(newString);
       
       
       
          new Ajax.Request('/?format=json&set='+newString, {
    onSuccess: function(response) {
        
        
       var data = response.responseText.evalJSON(true);
    // Handle the response content...
    
       console.log(data['dynamic']['listen']['set']['id']);
    }
});
        
          
    }
          
    </script>
</head>    
<body id="body" >

    <div id="header" data-lucky="27-20-25" ></div>
    <div id="content" data-lucky="22-24-26" ></div>
    <div id="footer"  data-lucky="23-28-21" ></div>
    <input type="button" value="Haz" onclick="haz();"  /> 
</body>
</html>